/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 island-decor.glb -r ../ 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/island-decor.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tree.geometry} material={materials.foliage} position={[0, 0.02, 0]} />
      <mesh geometry={nodes.house.geometry} material={materials.stone}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.tile} scale={0.869} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/island-decor.glb')
